//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClusterJobDocument
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public int ClusterCalculationId { get; set; }
        public int JobDocumentId { get; set; }
        public int ClusterId { get; set; }
    
        public virtual ClusterCalculation ClusterCalculation { get; set; }
        public virtual Cluster Cluster { get; set; }
        public virtual JobDocument JobDocument { get; set; }
        public virtual Job Job { get; set; }
    }
}
