//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cluster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cluster()
        {
            this.ClusterJobDocuments = new HashSet<ClusterJobDocument>();
            this.ClusterJobTerms = new HashSet<ClusterJobTerm>();
        }
    
        public int Id { get; set; }
        public int JobId { get; set; }
        public int ClusterCalculationId { get; set; }
        public byte[] CenterVectorSerialized { get; set; }
        public Nullable<float> Si { get; set; }
    
        public virtual ClusterCalculation ClusterCalculation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClusterJobDocument> ClusterJobDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClusterJobTerm> ClusterJobTerms { get; set; }
        public virtual Job Job { get; set; }
    }
}
