//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentDistance
    {
        public int JobId { get; set; }
        public int SourceDocumentId { get; set; }
        public int TargetDocumentId { get; set; }
        public float Distance { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Document SourceDocument { get; set; }
        public virtual Document TargetDocument { get; set; }
    }
}
