//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDocumentDistance
    {
        public int JobId { get; set; }
        public int SourceJobDocumentId { get; set; }
        public int TargetJobDocumentId { get; set; }
        public float Distance { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual JobDocument SourceJobDocument { get; set; }
        public virtual JobDocument TargetJobDocument { get; set; }
    }
}
