//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobDocument()
        {
            this.SourceJobDocumentDistances = new HashSet<JobDocumentDistance>();
            this.TargetJobDocumentDistances = new HashSet<JobDocumentDistance>();
        }
    
        public int JobId { get; set; }
        public int DocumentId { get; set; }
        public int OrdinalIndex { get; set; }
        public int Id { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobDocumentDistance> SourceJobDocumentDistances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobDocumentDistance> TargetJobDocumentDistances { get; set; }
    }
}
