//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SvdEntities : DbContext
    {
        public SvdEntities()
            : base("name=SvdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClusterCalculation> ClusterCalculations { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<JobDocument> JobDocuments { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobTerm> JobTerms { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<UMatrix> UMatrices { get; set; }
        public virtual DbSet<VMatrix> VMatrices { get; set; }
        public virtual DbSet<TermDocumentCount> TermDocumentCounts { get; set; }
        public virtual DbSet<ClusterJobDocument> ClusterJobDocuments { get; set; }
        public virtual DbSet<ClusterJobTerm> ClusterJobTerms { get; set; }
        public virtual DbSet<Cluster> Clusters { get; set; }
    }
}
